#!/bin/sh

# Control apt-cacher-service run|stop|start with docker
#
# This is just a very simple helper. Use docker directly
# for full options (see http://www.docker.com/)

name=apt-cacher-service
tag=inaetics/$name

start_srv() {
    docker start $name >/dev/null 2>&1
    if [ $? -gt 0 ]; then
      docker run --name $name -d -t -p 3142:3142 $tag  >/dev/null 2>&1
    fi
}

stop_srv() {
    docker stop $name >/dev/null 2>&1
    docker rm $name >/dev/null 2>&1
    exit
}

old_pwd=$PWD
cd $(dirname $0)

case "$1" in
  build)
    echo "Building $name ..."
    docker build -t $tag .
    ;;
  run)
    echo "Running $name" 
    start_srv
    trap stop_srv SIGHUP SIGINT SIGTERM
    while true; do sleep 10; done
    ;;
  start)
    echo "Starting $name" 
    start_srv
    ;;
  stop)
    echo "Stopping $name" 
    stop_srv
    ;;
  *)
    echo "Usage: $0 {build|run|start|stop}"
    exit 1
    ;;
esac

cd $old_pwd
### EOF
